
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CompanySegmentScalarFieldEnum = {
  segmentId: 'segmentId',
  segmentName: 'segmentName',
  description: 'description'
};

exports.Prisma.CompanyScalarFieldEnum = {
  companyId: 'companyId',
  urlImage: 'urlImage',
  companyName: 'companyName',
  companyStatus: 'companyStatus',
  companyTelpFax: 'companyTelpFax',
  companyCity: 'companyCity',
  companyAddress: 'companyAddress',
  companyEmail: 'companyEmail',
  npwp: 'npwp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  companyCode: 'companyCode',
  companyType: 'companyType',
  application: 'application'
};

exports.Prisma.CompanySegmentLinkScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  segmentId: 'segmentId'
};

exports.Prisma.Distro_PO_IncentiveScalarFieldEnum = {
  id: 'id',
  rangeFrom: 'rangeFrom',
  rangeTo: 'rangeTo',
  vehicle: 'vehicle',
  vehicleId: 'vehicleId',
  periodYear: 'periodYear',
  amount: 'amount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Distro_PO_HeaderScalarFieldEnum = {
  id: 'id',
  poNumber: 'poNumber',
  distributorName: 'distributorName',
  customerCode: 'customerCode',
  poDate: 'poDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  niterraPO: 'niterraPO',
  niterraSO: 'niterraSO',
  uuid: 'uuid'
};

exports.Prisma.Distro_PO_LineScalarFieldEnum = {
  id: 'id',
  vehicle: 'vehicle',
  vehicleId: 'vehicleId',
  category: 'category',
  spType: 'spType',
  partName: 'partName',
  partNumber: 'partNumber',
  qty: 'qty',
  price: 'price',
  purchaseOrderId: 'purchaseOrderId'
};

exports.Prisma.Distro_PO_MasterItemScalarFieldEnum = {
  id: 'id',
  vehicle: 'vehicle',
  vehicleId: 'vehicleId',
  category: 'category',
  productName: 'productName',
  spType: 'spType',
  itemId: 'itemId',
  isActive: 'isActive'
};

exports.Prisma.Distro_PO_MasterItem_Price_HeaderScalarFieldEnum = {
  id: 'id',
  description: 'description',
  createdAt: 'createdAt',
  createdBy: 'createdBy',
  updatedAt: 'updatedAt'
};

exports.Prisma.Distro_PO_MasterItem_Price_LineScalarFieldEnum = {
  id: 'id',
  headerId: 'headerId',
  customerCode: 'customerCode',
  customerName: 'customerName',
  itemId: 'itemId',
  itemName: 'itemName',
  price: 'price',
  activationDate: 'activationDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Distro_PO_MasterAchievementScalarFieldEnum = {
  id: 'id',
  customerCode: 'customerCode',
  customerName: 'customerName',
  city: 'city',
  targetQty: 'targetQty',
  targetAmount: 'targetAmount',
  vehicle: 'vehicle',
  vehicleId: 'vehicleId',
  periodYear: 'periodYear',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9ScalarFieldEnum = {
  formL9Id: 'formL9Id',
  companyId: 'companyId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9BankInfoScalarFieldEnum = {
  formL9BankInfoid: 'formL9BankInfoid',
  formL9Id: 'formL9Id',
  beneficiaryName: 'beneficiaryName',
  beneficiaryAddress: 'beneficiaryAddress',
  bankName: 'bankName',
  bankAddress: 'bankAddress',
  noRek: 'noRek',
  swiftCode: 'swiftCode',
  IBAN: 'IBAN',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9GeneralInformationScalarFieldEnum = {
  formGeneralInformationId: 'formGeneralInformationId',
  formL9Id: 'formL9Id',
  companyName: 'companyName',
  companyFoundingDate: 'companyFoundingDate',
  companyStatus: 'companyStatus',
  companyTelpFax: 'companyTelpFax',
  companyAddress: 'companyAddress',
  companyEmail: 'companyEmail',
  npwp: 'npwp',
  totalCapital: 'totalCapital',
  segmentId: 'segmentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9GeneralInformationContinueScalarFieldEnum = {
  formL9GeneralInformationContinueId: 'formL9GeneralInformationContinueId',
  formGeneralInformationId: 'formGeneralInformationId',
  permitsHeld: 'permitsHeld',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9ManagementScalarFieldEnum = {
  formL9ManagementId: 'formL9ManagementId',
  formL9Id: 'formL9Id',
  position: 'position',
  name: 'name',
  noTelpFaxHp: 'noTelpFaxHp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9EmployeScalarFieldEnum = {
  formL9EmployeId: 'formL9EmployeId',
  formL9Id: 'formL9Id',
  totalEmployees: 'totalEmployees',
  qualityControl: 'qualityControl',
  engineering: 'engineering',
  production: 'production',
  management: 'management',
  other: 'other',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9WorkExperienceScalarFieldEnum = {
  formL9WorkExperienceId: 'formL9WorkExperienceId',
  formL9Id: 'formL9Id',
  customerOrLocation: 'customerOrLocation',
  typeOfWork: 'typeOfWork',
  score: 'score',
  customerContactPerson: 'customerContactPerson',
  customerTelpFaxHp: 'customerTelpFaxHp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9OthersScalarFieldEnum = {
  formL9OthersId: 'formL9OthersId',
  formL9Id: 'formL9Id',
  haveCertificateISO: 'haveCertificateISO',
  haveCompanyOrganizationalStructure: 'haveCompanyOrganizationalStructure',
  haveQualityControlOrganizationalStructure: 'haveQualityControlOrganizationalStructure',
  haveProductWarranty: 'haveProductWarranty',
  haveExpiryDate: 'haveExpiryDate',
  haveAPD: 'haveAPD',
  haveAPDRegulation: 'haveAPDRegulation',
  isTopApplicable: 'isTopApplicable',
  paymentTime: 'paymentTime',
  agreeToConfidentialInformation: 'agreeToConfidentialInformation',
  understandingBreachesOfConfidentiality: 'understandingBreachesOfConfidentiality',
  signConfidentialityAgreement: 'signConfidentialityAgreement',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormL9CertificateISOScalarFieldEnum = {
  certificateISOId: 'certificateISOId',
  formL9OthersId: 'formL9OthersId',
  isoName: 'isoName',
  validityPeriodFrom: 'validityPeriodFrom',
  validityPeriodTo: 'validityPeriodTo',
  remakes: 'remakes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AllowedIpCorsScalarFieldEnum = {
  ip: 'ip'
};

exports.Prisma.MenuScalarFieldEnum = {
  menuId: 'menuId',
  sequence: 'sequence',
  parentId: 'parentId',
  icon: 'icon',
  application: 'application',
  menuName: 'menuName',
  redirect: 'redirect',
  isGlobal: 'isGlobal',
  isShow: 'isShow',
  isActive: 'isActive'
};

exports.Prisma.UserScalarFieldEnum = {
  userId: 'userId',
  email: 'email',
  application: 'application',
  password: 'password',
  isActive: 'isActive',
  sessionExpireDate: 'sessionExpireDate',
  createdDate: 'createdDate',
  updateDate: 'updateDate',
  blockedUntil: 'blockedUntil',
  failedLoginAttempts: 'failedLoginAttempts'
};

exports.Prisma.OtpVerifikasiScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  code: 'code',
  expireDate: 'expireDate'
};

exports.Prisma.LogsLoginScalarFieldEnum = {
  logsId: 'logsId',
  userId: 'userId',
  token: 'token',
  isActive: 'isActive',
  device: 'device',
  ip: 'ip',
  createdDate: 'createdDate',
  expireDate: 'expireDate'
};

exports.Prisma.RoleScalarFieldEnum = {
  roleId: 'roleId',
  roleName: 'roleName'
};

exports.Prisma.AccessScalarFieldEnum = {
  accessId: 'accessId',
  accessName: 'accessName'
};

exports.Prisma.ResetPasswordScalarFieldEnum = {
  resetId: 'resetId',
  userId: 'userId',
  token: 'token',
  createdDate: 'createdDate',
  expireDate: 'expireDate'
};

exports.Prisma.UserHasRoleAccessScalarFieldEnum = {
  userId: 'userId',
  roleId: 'roleId',
  accessId: 'accessId',
  menuId: 'menuId'
};

exports.Prisma.LinkedDeviceScalarFieldEnum = {
  deviceId: 'deviceId',
  clientDeviceUuid: 'clientDeviceUuid',
  userId: 'userId'
};

exports.Prisma.ProfileScalarFieldEnum = {
  userId: 'userId',
  companyId: 'companyId',
  fullName: 'fullName',
  urlImage: 'urlImage',
  phone: 'phone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  CompanySegment: 'CompanySegment',
  Company: 'Company',
  CompanySegmentLink: 'CompanySegmentLink',
  Distro_PO_Incentive: 'Distro_PO_Incentive',
  Distro_PO_Header: 'Distro_PO_Header',
  Distro_PO_Line: 'Distro_PO_Line',
  Distro_PO_MasterItem: 'Distro_PO_MasterItem',
  Distro_PO_MasterItem_Price_Header: 'Distro_PO_MasterItem_Price_Header',
  Distro_PO_MasterItem_Price_Line: 'Distro_PO_MasterItem_Price_Line',
  Distro_PO_MasterAchievement: 'Distro_PO_MasterAchievement',
  FormL9: 'FormL9',
  FormL9BankInfo: 'FormL9BankInfo',
  FormL9GeneralInformation: 'FormL9GeneralInformation',
  FormL9GeneralInformationContinue: 'FormL9GeneralInformationContinue',
  FormL9Management: 'FormL9Management',
  FormL9Employe: 'FormL9Employe',
  FormL9WorkExperience: 'FormL9WorkExperience',
  FormL9Others: 'FormL9Others',
  FormL9CertificateISO: 'FormL9CertificateISO',
  AllowedIpCors: 'AllowedIpCors',
  Menu: 'Menu',
  User: 'User',
  otpVerifikasi: 'otpVerifikasi',
  LogsLogin: 'LogsLogin',
  Role: 'Role',
  Access: 'Access',
  ResetPassword: 'ResetPassword',
  UserHasRoleAccess: 'UserHasRoleAccess',
  LinkedDevice: 'LinkedDevice',
  Profile: 'Profile'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
