
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
  Snapshot: 'Snapshot'
});

exports.Prisma.AX_SP_TypeScalarFieldEnum = {
  item_prefix: 'item_prefix',
  S_P_Type: 'S_P_Type'
};

exports.Prisma.Sales_D365ImporForm_OrderLinesScalarFieldEnum = {
  ID: 'ID',
  RequestedReceiptDate: 'RequestedReceiptDate',
  RequestedShipDate: 'RequestedShipDate',
  Customer: 'Customer',
  DeliveryName: 'DeliveryName',
  SalesOrder: 'SalesOrder',
  LineStatus: 'LineStatus',
  ItemNumber: 'ItemNumber',
  ProductName: 'ProductName',
  Quantity: 'Quantity',
  Unit: 'Unit',
  UnitPrice: 'UnitPrice',
  Discount: 'Discount',
  DiscountPercent: 'DiscountPercent',
  NetAmount: 'NetAmount',
  CreatedBy: 'CreatedBy',
  CreatedDateAndTime: 'CreatedDateAndTime',
  CustomerReference: 'CustomerReference',
  ItemSalesTaxGroup: 'ItemSalesTaxGroup',
  NTT_NonCommercial: 'NTT_NonCommercial',
  SalesTaxGroup: 'SalesTaxGroup',
  LineNumber: 'LineNumber',
  DescriptionForSalesReport: 'DescriptionForSalesReport',
  Text: 'Text'
};

exports.Prisma.Sales_D365ImporForm_SalesScalarFieldEnum = {
  ID: 'ID',
  SalesOrder: 'SalesOrder',
  SalesLineNumber: 'SalesLineNumber',
  CustomerCode: 'CustomerCode',
  CustomerName: 'CustomerName',
  CustomerReference: 'CustomerReference',
  ExternalItemNumber: 'ExternalItemNumber',
  ItemID: 'ItemID',
  ProductName: 'ProductName',
  ItemDescription: 'ItemDescription',
  SearchNameAll: 'SearchNameAll',
  SearchNameReleased: 'SearchNameReleased',
  SPType: 'SPType',
  VehicleID: 'VehicleID',
  MasterVehicle: 'MasterVehicle',
  ItemGroup: 'ItemGroup',
  PackingSlipID: 'PackingSlipID',
  PackingSlipDate: 'PackingSlipDate',
  PackingQty: 'PackingQty',
  YearDlv: 'YearDlv',
  MonthDlv: 'MonthDlv',
  ProductCategory: 'ProductCategory',
  ProcateName: 'ProcateName',
  Genuine: 'Genuine',
  Motor: 'Motor',
  OriginalInvoiceNo: 'OriginalInvoiceNo',
  SalesPrice: 'SalesPrice',
  DiscAmount: 'DiscAmount',
  DiscPercent: 'DiscPercent',
  ExchangeRate: 'ExchangeRate',
  Currency: 'Currency',
  SalesClass: 'SalesClass',
  AmountGrossCurrency: 'AmountGrossCurrency',
  AmountDiscountCurrency: 'AmountDiscountCurrency',
  AmountNetCurrency: 'AmountNetCurrency',
  AmountGrossLocalCurrency: 'AmountGrossLocalCurrency',
  AmountDiscountLocalCurrency: 'AmountDiscountLocalCurrency',
  AmountNetLocalCurrency: 'AmountNetLocalCurrency',
  Status_GIT: 'Status_GIT',
  Date_Inv: 'Date_Inv',
  Year_Inv: 'Year_Inv',
  Month_Inv: 'Month_Inv',
  City: 'City',
  Month_Odr: 'Month_Odr',
  CommercialStatus: 'CommercialStatus',
  VAT: 'VAT',
  STDCost: 'STDCost',
  GITCost: 'GITCost',
  PeriodDLV: 'PeriodDLV',
  PeriodINV: 'PeriodINV',
  DaysDueDateInv: 'DaysDueDateInv',
  NPWP: 'NPWP',
  TaxInvoiceNo: 'TaxInvoiceNo',
  DescriptionforSalesReport: 'DescriptionforSalesReport'
};

exports.Prisma.Sales_D365ImporForm_SalesBIScalarFieldEnum = {
  ID: 'ID',
  Company: 'Company',
  InvoiceDateYYMM: 'InvoiceDateYYMM',
  InvoiceDateYYYYMMDD: 'InvoiceDateYYYYMMDD',
  DueDate: 'DueDate',
  SOCreateDate: 'SOCreateDate',
  RequestReceiptDate: 'RequestReceiptDate',
  Invoice: 'Invoice',
  SONo: 'SONo',
  CustomerCode: 'CustomerCode',
  CustomerName: 'CustomerName',
  CustomerSearchName: 'CustomerSearchName',
  ItemCode: 'ItemCode',
  ItemName: 'ItemName',
  Division: 'Division',
  DivisionName: 'DivisionName',
  ProductCategory: 'ProductCategory',
  ProductCategoryName: 'ProductCategoryName',
  Country: 'Country',
  Area: 'Area',
  SalesPerson: 'SalesPerson',
  SalesPersonName: 'SalesPersonName',
  BusinessType: 'BusinessType',
  BusinessTypeName: 'BusinessTypeName',
  Design: 'Design',
  Brand: 'Brand',
  ProductCateMajor: 'ProductCateMajor',
  ProductCateMajorName: 'ProductCateMajorName',
  ProductCateMiddle: 'ProductCateMiddle',
  ProductCateMiddleName: 'ProductCateMiddleName',
  ProductCateMinor: 'ProductCateMinor',
  ProductCateMinorName: 'ProductCateMinorName',
  PackagingCountry: 'PackagingCountry',
  Quantity: 'Quantity',
  Currency: 'Currency',
  PriceByIVCurrency: 'PriceByIVCurrency',
  AmountByIVCurrency: 'AmountByIVCurrency',
  PriceByLocalCurrency: 'PriceByLocalCurrency',
  AmountByLocalCurrency: 'AmountByLocalCurrency',
  RecID: 'RecID',
  CustomerReference: 'CustomerReference',
  DescriptionForSalesReport: 'DescriptionForSalesReport',
  ItemGroup: 'ItemGroup',
  TaxPercent: 'TaxPercent',
  Tax: 'Tax',
  NetAmount: 'NetAmount',
  TaxInvoiceId: 'TaxInvoiceId',
  NPWP: 'NPWP',
  LineDisc: 'LineDisc',
  InvoiceAddress: 'InvoiceAddress',
  ExternalItemId: 'ExternalItemId'
};

exports.Prisma.Sales_D365ImporForm_SalesPackingQuantityScalarFieldEnum = {
  ID: 'ID',
  SalesOrder: 'SalesOrder',
  SalesLineNumber: 'SalesLineNumber',
  CustomerCode: 'CustomerCode',
  CustomerName: 'CustomerName',
  CustomerReference: 'CustomerReference',
  ExternalItemNumber: 'ExternalItemNumber',
  ItemID: 'ItemID',
  ProductName: 'ProductName',
  ItemDescription: 'ItemDescription',
  DescriptionforSalesReport: 'DescriptionforSalesReport',
  SearchNameAll: 'SearchNameAll',
  SearchNameReleased: 'SearchNameReleased',
  SPType: 'SPType',
  VehicleID: 'VehicleID',
  ItemGroup: 'ItemGroup',
  PackingSlipID: 'PackingSlipID',
  PackingSlipDeliveryDate: 'PackingSlipDeliveryDate',
  PackingQty: 'PackingQty',
  YearDlv: 'YearDlv',
  MonthDlv: 'MonthDlv',
  ProductCategory: 'ProductCategory',
  ProcateName: 'ProcateName',
  Genuine: 'Genuine',
  Motor: 'Motor',
  InvoiceNo: 'InvoiceNo',
  SalesPrice: 'SalesPrice',
  DiscAmount: 'DiscAmount',
  DiscPercent: 'DiscPercent',
  ExchangeRate: 'ExchangeRate',
  Currency: 'Currency',
  SalesClass: 'SalesClass',
  AmountGrossCurrency: 'AmountGrossCurrency',
  AmountDiscountCurrency: 'AmountDiscountCurrency',
  AmountNetCurrency: 'AmountNetCurrency',
  AmountGrossLocalCurrency: 'AmountGrossLocalCurrency',
  AmountDiscountLocalCurrency: 'AmountDiscountLocalCurrency',
  AmountNetLocalCurrency: 'AmountNetLocalCurrency',
  Status_GIT: 'Status_GIT',
  Date_Inv: 'Date_Inv',
  Year_Inv: 'Year_Inv',
  Month_Inv: 'Month_Inv',
  City: 'City',
  Month_Odr: 'Month_Odr',
  CommercialStatus: 'CommercialStatus',
  GITPrice: 'GITPrice',
  GITCost: 'GITCost'
};

exports.Prisma.SCM_D365_PickinglistScalarFieldEnum = {
  PickingRoute: 'PickingRoute',
  ItemNumber: 'ItemNumber',
  HandlingStatus: 'HandlingStatus',
  Description: 'Description',
  OrderQuantity: 'OrderQuantity',
  OrderUnit: 'OrderUnit',
  CWQuantity: 'CWQuantity',
  CWUnit: 'CWUnit',
  DeliveryDate: 'DeliveryDate',
  Quantity: 'Quantity',
  Picked: 'Picked',
  Id: 'Id'
};

exports.Prisma.SCM_D365ImporForm_ProductReceipt_2023ScalarFieldEnum = {
  ID: 'ID',
  PurchaseOrder: 'PurchaseOrder',
  VendorName: 'VendorName',
  Currency: 'Currency',
  PurchaseType: 'PurchaseType',
  InvoiceAccount: 'InvoiceAccount',
  OrderAccount: 'OrderAccount',
  Date: 'Date',
  DocumentDate: 'DocumentDate',
  ProductReceipt: 'ProductReceipt',
  Site: 'Site',
  Warehouse: 'Warehouse',
  InternalProductReceipt: 'InternalProductReceipt',
  OuterPackageNumber: 'OuterPackageNumber',
  LineNumber: 'LineNumber',
  Item: 'Item',
  Description: 'Description',
  Unit: 'Unit',
  Ordered: 'Ordered',
  ReceivedQuantity: 'ReceivedQuantity',
  PriceUnit: 'PriceUnit',
  RemainingQuantity: 'RemainingQuantity',
  Value: 'Value',
  ProductName: 'ProductName',
  DescriptionPurchaseReport: 'DescriptionPurchaseReport',
  LocalImport: 'LocalImport',
  ProCateName: 'ProCateName',
  SearchNameAll: 'SearchNameAll',
  SearchNameReleased: 'SearchNameReleased',
  ItemGroup: 'ItemGroup',
  Year: 'Year',
  Month: 'Month',
  Factor: 'Factor',
  Denominator: 'Denominator',
  Numerator: 'Numerator',
  QtyConversion: 'QtyConversion',
  UnitPrice: 'UnitPrice',
  RelUnRel: 'RelUnRel',
  ExchangeRate: 'ExchangeRate',
  CreatedBy: 'CreatedBy',
  CreatedDateTime: 'CreatedDateTime',
  DiscAmount: 'DiscAmount',
  DiscPercent: 'DiscPercent',
  CostLedgerVoucher: 'CostLedgerVoucher',
  InternalInvoiceId: 'InternalInvoiceId',
  LedgerVoucher: 'LedgerVoucher',
  Periode: 'Periode',
  Standard_Cost: 'Standard_Cost',
  Standard_Cost_Beneran: 'Standard_Cost_Beneran',
  UploadTime: 'UploadTime',
  ConfirmReceivedStatus: 'ConfirmReceivedStatus'
};

exports.Prisma.SCM_D365ImporForm_ProductReceiptReturnScalarFieldEnum = {
  ID: 'ID',
  PurchaseOrder: 'PurchaseOrder',
  VendorName: 'VendorName',
  Currency: 'Currency',
  PurchaseType: 'PurchaseType',
  InvoiceAccount: 'InvoiceAccount',
  OrderAccount: 'OrderAccount',
  Date: 'Date',
  DocumentDate: 'DocumentDate',
  ProductReceipt: 'ProductReceipt',
  Site: 'Site',
  Warehouse: 'Warehouse',
  InternalProductReceipt: 'InternalProductReceipt',
  OuterPackageNumber: 'OuterPackageNumber',
  LineNumber: 'LineNumber',
  Item: 'Item',
  Description: 'Description',
  Unit: 'Unit',
  Ordered: 'Ordered',
  ReceivedQuantity: 'ReceivedQuantity',
  PriceUnit: 'PriceUnit',
  RemainingQuantity: 'RemainingQuantity',
  Value: 'Value',
  ProductName: 'ProductName',
  DescriptionPurchaseReport: 'DescriptionPurchaseReport',
  LocalImport: 'LocalImport',
  ProCateName: 'ProCateName',
  SearchNameAll: 'SearchNameAll',
  SearchNameReleased: 'SearchNameReleased',
  ItemGroup: 'ItemGroup',
  Year: 'Year',
  Month: 'Month',
  Factor: 'Factor',
  Denominator: 'Denominator',
  Numerator: 'Numerator',
  QtyConversion: 'QtyConversion',
  UnitPrice: 'UnitPrice',
  RelUnRel: 'RelUnRel',
  ExchangeRate: 'ExchangeRate',
  CreatedBy: 'CreatedBy',
  CreatedDateTime: 'CreatedDateTime',
  DiscAmount: 'DiscAmount',
  DiscPercent: 'DiscPercent',
  CostLedgerVoucher: 'CostLedgerVoucher',
  InternalInvoiceId: 'InternalInvoiceId',
  LedgerVoucher: 'LedgerVoucher',
  Periode: 'Periode',
  Standard_Cost: 'Standard_Cost',
  Standard_Cost_Beneran: 'Standard_Cost_Beneran',
  ConfirmReceivedStatus: 'ConfirmReceivedStatus'
};

exports.Prisma.SCM_D365ImporForm_PurchaseBIScalarFieldEnum = {
  ID: 'ID',
  Company: 'Company',
  VendorCode: 'VendorCode',
  VendorName: 'VendorName',
  InvoiceDate: 'InvoiceDate',
  InvoiceID: 'InvoiceID',
  Line_No: 'Line_No',
  PONo: 'PONo',
  POLineNo: 'POLineNo',
  ItemGroup: 'ItemGroup',
  ItemId: 'ItemId',
  Text: 'Text',
  Quantity: 'Quantity',
  PurchaseUnit: 'PurchaseUnit',
  PurchasePrice: 'PurchasePrice',
  Discount: 'Discount',
  DiscountPercent: 'DiscountPercent',
  Amount: 'Amount',
  Currency: 'Currency',
  CompanyCurrencyAmount: 'CompanyCurrencyAmount',
  PurchaseReason: 'PurchaseReason',
  DeliveryDate: 'DeliveryDate',
  SectionCode: 'SectionCode',
  SectionName: 'SectionName',
  Voucher: 'Voucher',
  CostingVoucher: 'CostingVoucher',
  PRNo: 'PRNo',
  CustomerRequisition: 'CustomerRequisition'
};

exports.Prisma.SCM_D365ImporForm_PurchaseBI_trialScalarFieldEnum = {
  ID: 'ID',
  Company: 'Company',
  VendorCode: 'VendorCode',
  VendorName: 'VendorName',
  InvoiceDate: 'InvoiceDate',
  InvoiceID: 'InvoiceID',
  Line_No: 'Line_No',
  PONo: 'PONo',
  POLineNo: 'POLineNo',
  ItemGroup: 'ItemGroup',
  ItemId: 'ItemId',
  Text: 'Text',
  Quantity: 'Quantity',
  PurchaseUnit: 'PurchaseUnit',
  PurchasePrice: 'PurchasePrice',
  Discount: 'Discount',
  DiscountPercent: 'DiscountPercent',
  Amount: 'Amount',
  Currency: 'Currency',
  CompanyCurrencyAmount: 'CompanyCurrencyAmount',
  PurchaseReason: 'PurchaseReason',
  DeliveryDate: 'DeliveryDate',
  SectionCode: 'SectionCode',
  SectionName: 'SectionName',
  Voucher: 'Voucher',
  CostingVoucher: 'CostingVoucher',
  PRNo: 'PRNo',
  CustomerRequisition: 'CustomerRequisition'
};

exports.Prisma.SCM_D365ImporForm_PurchaseLinesScalarFieldEnum = {
  ID: 'ID',
  Purchase_order: 'Purchase_order',
  Vendor_account: 'Vendor_account',
  Line_number: 'Line_number',
  Item_number: 'Item_number',
  Product_name: 'Product_name',
  Description: 'Description',
  PRNo: 'PRNo',
  Line_status: 'Line_status',
  Quantity: 'Quantity',
  Deliver_reminder: 'Deliver_reminder',
  Unit: 'Unit',
  Unit_price: 'Unit_price',
  Discount: 'Discount',
  Net_amount: 'Net_amount',
  Created_by: 'Created_by',
  Created_at: 'Created_at'
};

exports.Prisma.SCM_D365ImporForm_StockManagementScalarFieldEnum = {
  ID: 'ID',
  ItemGroup: 'ItemGroup',
  Date: 'Date',
  Warehouse: 'Warehouse',
  Item: 'Item',
  Batch: 'Batch',
  InventoryUnit: 'InventoryUnit',
  BeginningBalanceQty: 'BeginningBalanceQty',
  BeginningBalanceAmount: 'BeginningBalanceAmount',
  TransferQtyPlus: 'TransferQtyPlus',
  TransferAmountPlus: 'TransferAmountPlus',
  ProductionQtyPlus: 'ProductionQtyPlus',
  ProductionAmountPlus: 'ProductionAmountPlus',
  PurchasedQtyPlus: 'PurchasedQtyPlus',
  PurchaseAmountPlus: 'PurchaseAmountPlus',
  AdjustQtyPlus: 'AdjustQtyPlus',
  AdjustAmountPlus: 'AdjustAmountPlus',
  CountingQtyPlus: 'CountingQtyPlus',
  CountingAmountPlus: 'CountingAmountPlus',
  TransferQtyMinus: 'TransferQtyMinus',
  TransferAmountMinus: 'TransferAmountMinus',
  SalesQtyMinus: 'SalesQtyMinus',
  SalesAmountMinus: 'SalesAmountMinus',
  ConsumptionQtyMinus: 'ConsumptionQtyMinus',
  ConsumptionAmountMinus: 'ConsumptionAmountMinus',
  AdjustQtyMinus: 'AdjustQtyMinus',
  AdjustAmountMinus: 'AdjustAmountMinus',
  CountingQtyMinus: 'CountingQtyMinus',
  CountingAmountMinus: 'CountingAmountMinus',
  EndingBalanceQuantity: 'EndingBalanceQuantity',
  EndingBalanceAmount: 'EndingBalanceAmount',
  Procate: 'Procate',
  ProductName: 'ProductName',
  DescriptionFromPurchaseReport: 'DescriptionFromPurchaseReport',
  DescriptionFromSalesReport: 'DescriptionFromSalesReport',
  Periode: 'Periode'
};

exports.Prisma.SysdiagramsScalarFieldEnum = {
  name: 'name',
  principal_id: 'principal_id',
  diagram_id: 'diagram_id',
  version: 'version',
  definition: 'definition'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  AX_SP_Type: 'AX_SP_Type',
  Sales_D365ImporForm_OrderLines: 'Sales_D365ImporForm_OrderLines',
  Sales_D365ImporForm_Sales: 'Sales_D365ImporForm_Sales',
  Sales_D365ImporForm_SalesBI: 'Sales_D365ImporForm_SalesBI',
  Sales_D365ImporForm_SalesPackingQuantity: 'Sales_D365ImporForm_SalesPackingQuantity',
  SCM_D365_Pickinglist: 'SCM_D365_Pickinglist',
  SCM_D365ImporForm_ProductReceipt_2023: 'SCM_D365ImporForm_ProductReceipt_2023',
  SCM_D365ImporForm_ProductReceiptReturn: 'SCM_D365ImporForm_ProductReceiptReturn',
  SCM_D365ImporForm_PurchaseBI: 'SCM_D365ImporForm_PurchaseBI',
  SCM_D365ImporForm_PurchaseBI_trial: 'SCM_D365ImporForm_PurchaseBI_trial',
  SCM_D365ImporForm_PurchaseLines: 'SCM_D365ImporForm_PurchaseLines',
  SCM_D365ImporForm_StockManagement: 'SCM_D365ImporForm_StockManagement',
  sysdiagrams: 'sysdiagrams'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
